# Generated by Django 6.0.7 on 2026-07-27 08:18

import django.db.models.deletion
from django.db import migrations, models


def backfill_discipline(apps, schema_editor):
    Section = apps.get_model("projects", "Section")
    Discipline = apps.get_model("accounts", "Discipline")
    for section in Section.objects.all():
        code = (section.code or "").strip() or "OTHER"
        discipline, _created = Discipline.objects.get_or_create(
            code=code, defaults={"name": section.code or code}
        )
        section.discipline_id = discipline.pk
        section.save(update_fields=["discipline"])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_discipline_other_alter_user_disciplines'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='discipline',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sections', to='accounts.discipline'),
        ),
        migrations.RunPython(backfill_discipline, noop),
        migrations.RemoveField(
            model_name='section',
            name='code',
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ['discipline__code']},
        ),
    ]
