# Generated by Django 6.0.7 on 2026-07-27 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_section_discipline'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='district',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='region',
            field=models.CharField(blank=True, choices=[('tashkent_city', 'Toshkent shahri'), ('tashkent', 'Toshkent viloyati'), ('andijon', 'Andijon viloyati'), ('fargona', "Farg'ona viloyati"), ('namangan', 'Namangan viloyati'), ('sirdaryo', 'Sirdaryo viloyati'), ('jizzax', 'Jizzax viloyati'), ('samarqand', 'Samarqand viloyati'), ('buxoro', 'Buxoro viloyati'), ('navoiy', 'Navoiy viloyati'), ('qashqadaryo', 'Qashqadaryo viloyati'), ('surxondaryo', 'Surxondaryo viloyati'), ('xorazm', 'Xorazm viloyati'), ('qoraqalpogiston', "Qoraqalpog'iston Respublikasi")], max_length=30, null=True),
        ),
    ]
