# Generated by Django 6.0.7 on 2026-07-27 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_project_district_alter_project_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='region',
            field=models.CharField(blank=True, choices=[('tashkent_city', 'Tashkent city'), ('tashkent', 'Tashkent region'), ('andijon', 'Andijan region'), ('fargona', 'Fergana region'), ('namangan', 'Namangan region'), ('sirdaryo', 'Sirdaryo region'), ('jizzax', 'Jizzakh region'), ('samarqand', 'Samarkand region'), ('buxoro', 'Bukhara region'), ('navoiy', 'Navoi region'), ('qashqadaryo', 'Kashkadarya region'), ('surxondaryo', 'Surkhandarya region'), ('xorazm', 'Khorezm region'), ('qoraqalpogiston', 'Republic of Karakalpakstan')], max_length=30, null=True, verbose_name='Region'),
        ),
    ]
