# Generated by Django 6.0.7 on 2026-08-03 13:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_alter_project_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='client_contact_person',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='client_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='client_notes',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='client_position',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='client_stir',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator('^\\d+$', 'STIR must contain digits only.')]),
        ),
        migrations.AddField(
            model_name='project',
            name='client_type',
            field=models.CharField(blank=True, choices=[('legal_entity', 'Legal entity'), ('individual', 'Individual')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='construction_area',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='construction_type',
            field=models.CharField(blank=True, choices=[('new', 'New construction'), ('reconstruction', 'Reconstruction'), ('capital_repair', 'Capital repair'), ('expansion', 'Expansion')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='construction_volume',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='funding_source',
            field=models.CharField(blank=True, choices=[('own_funds', "Client's own funds"), ('state_budget', 'State budget'), ('loan', 'Loan funds'), ('investment', 'Investment'), ('other', 'Other')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='land_area',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='object_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='sector',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
