# Generated by Django 6.0.7 on 2026-08-03 13:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_project_client_contact_person_project_client_email_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subobject',
            options={'ordering': ['position', 'name']},
        ),
        migrations.AddField(
            model_name='subobject',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subobject',
            name='description',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='subobject',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subobject',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20),
        ),
        migrations.AddField(
            model_name='subobject',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='SubObjectWorker',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('lead', 'Lead'), ('engineer', 'Engineer'), ('architect', 'Architect'), ('electrician', 'Electrician'), ('estimator', 'Estimator'), ('supervisor', 'Supervisor')], default='engineer', max_length=20)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In progress'), ('review', 'Review'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('sub_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workers', to='projects.subobject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_object_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['assigned_at'],
                'constraints': [models.UniqueConstraint(fields=('sub_object', 'user'), name='unique_sub_object_worker')],
            },
        ),
    ]
