# Generated by Django 6.0.7 on 2026-08-07 01:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_user_role'),
        ('projects', '0008_alter_subobject_options_subobject_deadline_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubObjectDiscipline',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('not_started', 'Not started'), ('in_progress', 'In progress'), ('review', 'Review'), ('completed', 'Completed')], default='not_started', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['discipline__code'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='subobjectworker',
            name='unique_sub_object_worker',
        ),
        migrations.AddField(
            model_name='subobjectdiscipline',
            name='assignee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_sub_object_disciplines', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subobjectdiscipline',
            name='discipline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_object_disciplines', to='accounts.discipline'),
        ),
        migrations.AddField(
            model_name='subobjectdiscipline',
            name='sub_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disciplines', to='projects.subobject'),
        ),
        migrations.RemoveField(
            model_name='subobjectworker',
            name='sub_object',
        ),
        migrations.RemoveField(
            model_name='subobjectworker',
            name='user',
        ),
        migrations.AddConstraint(
            model_name='subobjectdiscipline',
            constraint=models.UniqueConstraint(fields=('sub_object', 'discipline'), name='unique_sub_object_discipline'),
        ),
        migrations.DeleteModel(
            name='SubObjectWorker',
        ),
    ]
