# Generated by Django 6.0.7 on 2026-08-07 12:19

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_user_role'),
        ('projects', '0009_subobjectdiscipline_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='subobject',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pod_objects', to='projects.subobject', verbose_name='Pod object of'),
        ),
        migrations.AlterField(
            model_name='project',
            name='address',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='project',
            name='budget',
            field=models.FloatField(default=0, verbose_name='Budget'),
        ),
        migrations.AlterField(
            model_name='project',
            name='client_contact',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Client contact'),
        ),
        migrations.AlterField(
            model_name='project',
            name='client_contact_person',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Client contact person'),
        ),
        migrations.AlterField(
            model_name='project',
            name='client_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='project',
            name='client_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Client name'),
        ),
        migrations.AlterField(
            model_name='project',
            name='client_notes',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='Client notes'),
        ),
        migrations.AlterField(
            model_name='project',
            name='client_position',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Client position'),
        ),
        migrations.AlterField(
            model_name='project',
            name='client_stir',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator('^\\d+$', 'STIR must contain digits only.')], verbose_name='STIR'),
        ),
        migrations.AlterField(
            model_name='project',
            name='client_type',
            field=models.CharField(blank=True, choices=[('legal_entity', 'Legal entity'), ('individual', 'Individual')], max_length=20, null=True, verbose_name='Client type'),
        ),
        migrations.AlterField(
            model_name='project',
            name='construction_area',
            field=models.FloatField(blank=True, null=True, verbose_name='Construction area'),
        ),
        migrations.AlterField(
            model_name='project',
            name='construction_type',
            field=models.CharField(blank=True, choices=[('new', 'New construction'), ('reconstruction', 'Reconstruction'), ('capital_repair', 'Capital repair'), ('expansion', 'Expansion')], max_length=20, null=True, verbose_name='Construction type'),
        ),
        migrations.AlterField(
            model_name='project',
            name='construction_volume',
            field=models.FloatField(blank=True, null=True, verbose_name='Construction volume'),
        ),
        migrations.AlterField(
            model_name='project',
            name='deadline',
            field=models.DateField(blank=True, null=True, verbose_name='Deadline'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='project',
            name='funding_source',
            field=models.CharField(blank=True, choices=[('own_funds', "Client's own funds"), ('state_budget', 'State budget'), ('loan', 'Loan funds'), ('investment', 'Investment'), ('other', 'Other')], max_length=20, null=True, verbose_name='Funding source'),
        ),
        migrations.AlterField(
            model_name='project',
            name='land_area',
            field=models.FloatField(blank=True, null=True, verbose_name='Land area'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='project',
            name='object_type',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Object type'),
        ),
        migrations.AlterField(
            model_name='project',
            name='paid_amount',
            field=models.FloatField(default=0, verbose_name='Paid amount'),
        ),
        migrations.AlterField(
            model_name='project',
            name='sector',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Sector'),
        ),
        migrations.AlterField(
            model_name='project',
            name='stage',
            field=models.CharField(choices=[('concept', 'Concept'), ('preliminary', 'Preliminary design'), ('working_docs', 'Working documentation'), ('expertise', 'Expertise'), ('construction', 'Construction')], default='concept', max_length=20, verbose_name='Stage'),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Start date'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('on_hold', 'On hold'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='active', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='projectmember',
            name='can_edit',
            field=models.BooleanField(default=True, verbose_name='Can edit'),
        ),
        migrations.AlterField(
            model_name='projectmember',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Expires at'),
        ),
        migrations.AlterField(
            model_name='projectmember',
            name='role_in_project',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Role in project'),
        ),
        migrations.AlterField(
            model_name='projectmember',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_memberships', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='section',
            name='discipline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sections', to='accounts.discipline', verbose_name='Discipline'),
        ),
        migrations.AlterField(
            model_name='section',
            name='gip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gip_sections', to=settings.AUTH_USER_MODEL, verbose_name='GIP'),
        ),
        migrations.AlterField(
            model_name='section',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='section',
            name='status',
            field=models.CharField(choices=[('not_started', 'Not started'), ('in_progress', 'In progress'), ('review', 'Review'), ('completed', 'Completed')], default='not_started', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='section',
            name='sub_object',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sections', to='projects.subobject', verbose_name='Sub-object'),
        ),
        migrations.AlterField(
            model_name='subobject',
            name='address',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='subobject',
            name='deadline',
            field=models.DateField(blank=True, null=True, verbose_name='Deadline'),
        ),
        migrations.AlterField(
            model_name='subobject',
            name='description',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='subobject',
            name='gip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gip_sub_objects', to=settings.AUTH_USER_MODEL, verbose_name='GIP'),
        ),
        migrations.AlterField(
            model_name='subobject',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='subobject',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20, verbose_name='Priority'),
        ),
        migrations.AlterField(
            model_name='subobject',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Start date'),
        ),
        migrations.AlterField(
            model_name='subobject',
            name='status',
            field=models.CharField(choices=[('not_started', 'Not started'), ('in_progress', 'In progress'), ('review', 'Review'), ('completed', 'Completed')], default='not_started', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='subobjectdiscipline',
            name='assignee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_sub_object_disciplines', to=settings.AUTH_USER_MODEL, verbose_name='Assignee'),
        ),
        migrations.AlterField(
            model_name='subobjectdiscipline',
            name='deadline',
            field=models.DateField(blank=True, null=True, verbose_name='Deadline'),
        ),
        migrations.AlterField(
            model_name='subobjectdiscipline',
            name='status',
            field=models.CharField(choices=[('not_started', 'Not started'), ('in_progress', 'In progress'), ('review', 'Review'), ('completed', 'Completed')], default='not_started', max_length=20, verbose_name='Status'),
        ),
    ]
