# Generated by Django 6.0.7 on 2026-08-09 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_subobject_parent_alter_project_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='currency',
            field=models.CharField(choices=[('UZS', "So'm"), ('USD', 'Dollar')], default='UZS', max_length=10, verbose_name='Currency'),
        ),
    ]
