# Generated by Django 6.0.7 on 2026-08-09 11:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_project_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='subobjectdiscipline',
            name='progress',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Progress, %'),
        ),
        migrations.AddField(
            model_name='subobjectdiscipline',
            name='weight',
            field=models.PositiveSmallIntegerField(default=0, help_text="This discipline's share of the sub-object's progress. All disciplines of a sub-object must sum to 100%.", validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Weight, %'),
        ),
    ]
