# Generated by Django 6.0.7 on 2026-08-10 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_subobjectdiscipline_progress_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='client_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Customer'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Project name'),
        ),
    ]
