# Generated by Django 6.0.7 on 2026-09-02 09:01

import apps.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_alter_project_client_name_alter_project_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, help_text='Cover photo or render shown on the project card.', null=True, upload_to='projects/%Y/%m/', validators=[apps.core.validators.MaxFileSizeValidator(8), apps.core.validators.AllowedExtensionsValidator(('jpg', 'jpeg', 'png', 'webp'))], verbose_name='Project image'),
        ),
    ]
