# Generated by Django 6.0.7 on 2026-07-28 05:05

import apps.core.validators
import apps.tasks.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_taskattachment_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskattachment',
            name='file',
            field=models.FileField(upload_to=apps.tasks.models.task_attachment_upload_to, validators=[apps.core.validators.MaxFileSizeValidator(25)]),
        ),
    ]
