# Generated by Django 6.0.7 on 2026-08-07 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_task_options_task_position_task_sub_object_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='task',
            name='position',
        ),
        migrations.RemoveField(
            model_name='task',
            name='sub_object',
        ),
        migrations.DeleteModel(
            name='TaskChecklistItem',
        ),
    ]
