# Generated by Django 6.0.7 on 2026-08-22 06:05

import apps.core.validators
import apps.tasks.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_task_reviewer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskattachment',
            name='file',
            field=models.FileField(upload_to=apps.tasks.models.task_attachment_upload_to, validators=[apps.core.validators.MaxFileSizeValidator(25), apps.core.validators.AllowedExtensionsValidator()]),
        ),
    ]
