# Generated by Django 6.0.7 on 2026-07-27 07:35

import uuid
from django.db import migrations, models

INITIAL_DISCIPLINES = [
    ("AR", "Arxitektura"),
    ("KR", "Konstruksiya"),
]


def seed_disciplines(apps, schema_editor):
    Discipline = apps.get_model("accounts", "Discipline")
    for code, name in INITIAL_DISCIPLINES:
        Discipline.objects.get_or_create(code=code, defaults={"name": name})


def unseed_disciplines(apps, schema_editor):
    Discipline = apps.get_model("accounts", "Discipline")
    Discipline.objects.filter(code__in=[code for code, _ in INITIAL_DISCIPLINES]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_notification_channels'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='discipline_other',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='disciplines',
            field=models.ManyToManyField(blank=True, related_name='users', to='accounts.discipline'),
        ),
        migrations.RunPython(seed_disciplines, unseed_disciplines),
    ]
