# Generated by Django 6.0.7 on 2026-07-27 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_discipline_user_discipline_other_user_disciplines'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='discipline_other',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Other discipline'),
        ),
        migrations.AlterField(
            model_name='user',
            name='disciplines',
            field=models.ManyToManyField(blank=True, related_name='users', to='accounts.discipline', verbose_name='Disciplines'),
        ),
    ]
