# Generated by Django 6.0.7 on 2026-07-28 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_discipline_other_alter_user_disciplines'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('finance', 'Finance'), ('gip', 'GIP'), ('gip_assistant', 'GIP assistant'), ('designer', 'Designer'), ('reviewer', 'Reviewer'), ('client', 'Client')], default='designer', max_length=20),
        ),
    ]
