# Generated by Django 6.0.7 on 2026-08-22 06:05

import apps.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', validators=[apps.core.validators.MaxFileSizeValidator(2), apps.core.validators.AllowedExtensionsValidator(('png', 'jpg', 'jpeg', 'gif', 'webp'))]),
        ),
    ]
