# Generated by Django 6.0.7 on 2026-07-28 11:55

import apps.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_alter_contract_file'),
        ('projects', '0006_alter_project_region'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('notes', models.CharField(blank=True, max_length=1000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CostCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20)),
                ('category', models.CharField(max_length=255)),
                ('budget', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_codes', to='projects.project')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='PaymentRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payment_type', models.CharField(choices=[('subcontract', 'Subcontract'), ('advance', 'Advance'), ('invoice', 'Invoice')], default='invoice', max_length=20)),
                ('amount', models.FloatField()),
                ('retainage_rate', models.FloatField(default=0.05)),
                ('retainage_amount', models.FloatField(default=0)),
                ('comment', models.CharField(blank=True, max_length=1000, null=True)),
                ('invoice_file', models.FileField(blank=True, null=True, upload_to='payment_requests/%Y/%m/', validators=[apps.core.validators.MaxFileSizeValidator(25)])),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_requests', to='finance.contractor')),
                ('cost_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_requests', to='finance.costcode')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_requests', to='projects.project')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_requests', to=settings.AUTH_USER_MODEL)),
                ('sub_object', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_requests', to='projects.subobject')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentApprovalStage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stage_order', models.PositiveIntegerField()),
                ('stage_name', models.CharField(max_length=100)),
                ('required_role', models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('finance', 'Finance'), ('gip', 'GIP'), ('gip_assistant', 'GIP assistant'), ('designer', 'Designer'), ('reviewer', 'Reviewer'), ('client', 'Client')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('skipped', 'Skipped')], default='pending', max_length=20)),
                ('comment', models.CharField(blank=True, max_length=1000, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_approval_stages', to=settings.AUTH_USER_MODEL)),
                ('payment_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_stages', to='finance.paymentrequest')),
            ],
            options={
                'ordering': ['stage_order'],
            },
        ),
        migrations.AddConstraint(
            model_name='costcode',
            constraint=models.UniqueConstraint(fields=('project', 'code'), name='unique_project_cost_code'),
        ),
    ]
