# Generated by Django 6.0.7 on 2026-08-10 08:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_contractor_costcode_paymentrequest_and_more'),
        ('projects', '0012_subobjectdiscipline_progress_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usd_rate', models.FloatField(default=12700)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='contract',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='project',
        ),
        migrations.RemoveField(
            model_name='paymentrequest',
            name='contractor',
        ),
        migrations.RemoveConstraint(
            model_name='costcode',
            name='unique_project_cost_code',
        ),
        migrations.RemoveField(
            model_name='paymentrequest',
            name='cost_code',
        ),
        migrations.RemoveField(
            model_name='paymentapprovalstage',
            name='payment_request',
        ),
        migrations.RemoveField(
            model_name='paymentapprovalstage',
            name='reviewer',
        ),
        migrations.RemoveField(
            model_name='paymentrequest',
            name='project',
        ),
        migrations.RemoveField(
            model_name='paymentrequest',
            name='requested_by',
        ),
        migrations.RemoveField(
            model_name='paymentrequest',
            name='sub_object',
        ),
        migrations.AddField(
            model_name='employeecontract',
            name='currency',
            field=models.CharField(choices=[('UZS', "So'm"), ('USD', 'Dollar')], default='UZS', max_length=10),
        ),
        migrations.AddField(
            model_name='employeecontract',
            name='pod_object',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_contracts_as_pod_object', to='projects.subobject', verbose_name='Pod-object'),
        ),
        migrations.AddField(
            model_name='employeecontract',
            name='sub_object',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_contracts', to='projects.subobject', verbose_name='Object'),
        ),
        migrations.AddField(
            model_name='financialrecord',
            name='account',
            field=models.CharField(blank=True, choices=[('usd_bank', 'Dollar hisob'), ('uzs_bank', "So'm hisob"), ('usd_cash', 'Naqd pul (USD)')], max_length=20, null=True, verbose_name='Account'),
        ),
        migrations.AddField(
            model_name='financialrecord',
            name='sub_object',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financial_records', to='projects.subobject', verbose_name='Object / pod-object'),
        ),
        migrations.AlterField(
            model_name='financialrecord',
            name='type',
            field=models.CharField(choices=[('income', 'Income'), ('expense', 'Expense'), ('advance', 'Advance'), ('payment', 'Salary')], max_length=20),
        ),
        migrations.AddField(
            model_name='financesettings',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Contract',
        ),
        migrations.DeleteModel(
            name='Contractor',
        ),
        migrations.RemoveField(
            model_name='costcode',
            name='project',
        ),
        migrations.DeleteModel(
            name='PaymentApprovalStage',
        ),
        migrations.DeleteModel(
            name='PaymentRequest',
        ),
        migrations.DeleteModel(
            name='CostCode',
        ),
    ]
