# Generated by Django 6.0.7 on 2026-08-10 13:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_financesettings_remove_contract_created_by_and_more'),
        ('projects', '0012_subobjectdiscipline_progress_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeecontract',
            name='advance',
            field=models.FloatField(default=0, verbose_name='Advance'),
        ),
        migrations.AlterField(
            model_name='employeecontract',
            name='amount',
            field=models.FloatField(verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='employeecontract',
            name='currency',
            field=models.CharField(choices=[('UZS', "So'm"), ('USD', 'Dollar')], default='UZS', max_length=10, verbose_name='Currency'),
        ),
        migrations.AlterField(
            model_name='employeecontract',
            name='notes',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='employeecontract',
            name='paid',
            field=models.FloatField(default=0, verbose_name='Paid'),
        ),
        migrations.AlterField(
            model_name='employeecontract',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_contracts', to='projects.project', verbose_name='Project'),
        ),
        migrations.AlterField(
            model_name='employeecontract',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('completed', 'Completed'), ('terminated', 'Terminated')], default='active', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='employeecontract',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_contracts', to=settings.AUTH_USER_MODEL, verbose_name='Employee'),
        ),
        migrations.AlterField(
            model_name='financialrecord',
            name='amount',
            field=models.FloatField(verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='financialrecord',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='financialrecord',
            name='currency',
            field=models.CharField(default='UZS', max_length=10, verbose_name='Currency'),
        ),
        migrations.AlterField(
            model_name='financialrecord',
            name='date',
            field=models.DateField(verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='financialrecord',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='financialrecord',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_records', to='projects.project', verbose_name='Project'),
        ),
        migrations.AlterField(
            model_name='financialrecord',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='financialrecord',
            name='type',
            field=models.CharField(choices=[('income', 'Income'), ('expense', 'Expense'), ('advance', 'Advance'), ('payment', 'Salary')], max_length=20, verbose_name='Type'),
        ),
    ]
