# Generated by Django 6.0.7 on 2026-08-13 03:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_alter_employeecontract_advance_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialrecord',
            name='category',
            field=models.CharField(blank=True, choices=[('rent', 'Rent'), ('tax', 'Tax'), ('utilities', 'Utilities'), ('supplies', 'Office supplies'), ('materials', 'Materials'), ('salary', 'Salary'), ('other', 'Other')], max_length=100, null=True, verbose_name='Category'),
        ),
        migrations.CreateModel(
            name='AdministrativeExpense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('tax', 'Tax'), ('rent', 'Rent'), ('utilities', 'Utilities'), ('supplies', 'Office supplies'), ('other', 'Other')], max_length=20, verbose_name='Category')),
                ('amount', models.FloatField(verbose_name='Amount')),
                ('currency', models.CharField(choices=[('UZS', "So'm"), ('USD', 'Dollar')], default='UZS', max_length=10, verbose_name='Currency')),
                ('period', models.CharField(choices=[('month', 'Monthly'), ('quarter', 'Quarterly'), ('year', 'Yearly')], max_length=10, verbose_name='Period')),
                ('date', models.DateField(verbose_name='Date')),
                ('note', models.CharField(blank=True, max_length=500, null=True, verbose_name='Note')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
