# Generated by Django 6.0.7 on 2026-08-20 17:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_alter_financialrecord_category_administrativeexpense'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrativeexpense',
            name='category',
            field=models.CharField(max_length=100, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='employeecontract',
            name='amount',
            field=models.FloatField(verbose_name='Budget'),
        ),
        migrations.CreateModel(
            name='FinanceCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Category name')),
                ('type', models.CharField(choices=[('income', 'Income'), ('expense', 'Expense'), ('admin', 'Administrative')], default='expense', max_length=20, verbose_name='Type')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Finance Category',
                'verbose_name_plural': 'Finance Categories',
                'ordering': ['name'],
            },
        ),
    ]
