# Generated by Django 6.0.8 on 2026-08-23 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_alter_administrativeexpense_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialrecord',
            name='exchange_rate',
            field=models.FloatField(blank=True, help_text='USD rate used at the moment of the operation.', null=True, verbose_name='Exchange rate'),
        ),
    ]
