# Generated by Django 6.0.7 on 2026-07-14 11:34

import apps.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='documents/%Y/%m/', validators=[apps.core.validators.MaxFileSizeValidator(50)]),
        ),
        migrations.AlterField(
            model_name='documentversion',
            name='file',
            field=models.FileField(upload_to='documents/%Y/%m/', validators=[apps.core.validators.MaxFileSizeValidator(50)]),
        ),
    ]
