# Generated by Django 6.0.7 on 2026-08-10 19:36

import apps.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_alter_document_file_alter_documentversion_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalstage',
            name='response_file',
            field=models.FileField(blank=True, null=True, upload_to='approval_responses/%Y/%m/', validators=[apps.core.validators.MaxFileSizeValidator(50)]),
        ),
    ]
