# Generated by Django 6.0.7 on 2026-08-19 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_approvalstage_response_file'),
        ('tasks', '0005_alter_task_options_remove_task_position_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='source_task',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_document', to='tasks.task'),
        ),
    ]
