# Generated by Django 6.0.7 on 2026-08-22 06:05

import apps.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_document_source_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvalstage',
            name='response_file',
            field=models.FileField(blank=True, null=True, upload_to='approval_responses/%Y/%m/', validators=[apps.core.validators.MaxFileSizeValidator(50), apps.core.validators.AllowedExtensionsValidator()]),
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='documents/%Y/%m/', validators=[apps.core.validators.MaxFileSizeValidator(50), apps.core.validators.AllowedExtensionsValidator()]),
        ),
        migrations.AlterField(
            model_name='documentversion',
            name='file',
            field=models.FileField(upload_to='documents/%Y/%m/', validators=[apps.core.validators.MaxFileSizeValidator(50), apps.core.validators.AllowedExtensionsValidator()]),
        ),
    ]
