# Generated by Django 6.0.7 on 2026-07-14 06:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AILog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('agent', models.CharField(blank=True, db_index=True, max_length=64)),
                ('provider', models.CharField(blank=True, max_length=32)),
                ('model', models.CharField(blank=True, max_length=64)),
                ('system', models.TextField(blank=True)),
                ('prompt', models.TextField(blank=True)),
                ('response', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('success', 'Muvaffaqiyatli'), ('empty', "Bo'sh javob"), ('error', 'Xato')], max_length=16)),
                ('error', models.TextField(blank=True)),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'AI log',
                'verbose_name_plural': 'AI loglar',
                'ordering': ['-created_at'],
            },
        ),
    ]
