# Generated by Django 6.0.7 on 2026-07-08 12:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('template_type', models.CharField(choices=[('contract', 'Contract'), ('act', 'Act'), ('appendix', 'Appendix'), ('invoice', 'Invoice'), ('other', 'Other')], default='contract', max_length=20)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('content', models.TextField(help_text='Mail-merge style content using {{placeholder}} tokens.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
