# Generated by Django 6.0.7 on 2026-07-14 06:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('chat_id', models.CharField(db_index=True, max_length=64)),
                ('kind', models.CharField(choices=[('command', 'Buyruq'), ('message', 'Xabar'), ('other', 'Boshqa')], default='message', max_length=16)),
                ('text', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='telegram_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Telegram hodisa',
                'verbose_name_plural': 'Telegram hodisalar',
                'ordering': ['-created_at'],
            },
        ),
    ]
