# Generated by Django 6.0.7 on 2026-07-17 04:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0002_telegramevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramChat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('chat_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('language', models.CharField(choices=[('uz', 'Oʻzbekcha'), ('ru', 'Русский'), ('en', 'English')], default='uz', max_length=8)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
